# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - identifier: research
    name: Research
    weight: 20
  - name: Publications
    parent: research
    url: /#publications
    weight: 21
  - name: Working Papers
    parent: research
    url: /#working-papers
    weight: 22
  - name: Ongoing Projects
    parent: research
    url: /#wip
    weight: 23
  - name: Policy
    url: /#policy
    weight: 30
  - name: Skills
    url: /#skills
    weight: 40
  - name: Teaching
    url: /#teaching
    weight: 50
  - name: CV
    url: /uploads/madera_cv.pdf
    weight: 60
